# Generated by Django 5.1 on 2024-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='title',
            field=models.CharField(default='Spotify Wrap', max_length=255),
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='top_track_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
