# Generated by Django 5.1 on 2024-11-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapped', '0002_spotifywrap_title_spotifywrap_top_track_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='album_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='track_images',
            field=models.JSONField(default=list),
        ),
    ]
