# Generated by Django 5.1 on 2024-11-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapped', '0003_spotifywrap_album_images_spotifywrap_track_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrap',
            name='album_images',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='track_images',
        ),
    ]
