# Generated by Django 5.1 on 2024-11-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapped', '0004_remove_spotifywrap_album_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='wrap_data',
            new_name='top_tracks',
        ),
    ]
