# Generated by Django 5.1 on 2024-11-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapped', '0005_rename_wrap_data_spotifywrap_top_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='top_tracks',
            new_name='wrap_data',
        ),
    ]
